_BASE_: "../Base-MGN.yml"

MODEL:
  BACKBONE:
    WITH_IBN: True
    # PRETRAIN: True
    # PRETRAIN_PATH: "/data_4t/xk/ReID/fast-reid-master/model_zoo/market_mgn_R50-ibn.pth"

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: "logs/market1501/mgn_R50-ibn"
